<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.10" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SLK.TryEdu.ModuleCoinBlazor\SLK.TryEdu.ModuleCoinBlazor.csproj" />
	  <ProjectReference Include="..\SLK.TryEdu.ModuleContentBlazor\SLK.TryEdu.ModuleContentBlazor.csproj" />
	  <ProjectReference Include="..\SLK.TryEdu.ModuleEmployeeBlazor\SLK.TryEdu.ModuleEmployeeBlazor.csproj" />
	  <ProjectReference Include="..\SLK.TryEdu.ModulePartnerBlazor\SLK.TryEdu.ModulePartnerBlazor.csproj" />
	   <ProjectReference Include="..\SLK.TryEdu.ModuleUserBlazor\SLK.TryEdu.ModuleUserBlazor.csproj" />
	  <ProjectReference Include="..\SLK.TryEdu.ModuleManagementBlazor\SLK.TryEdu.ModuleManagementBlazor.csproj" />
	  <ProjectReference Include="..\SLK.TryEdu.ModuleSettingBlazor\SLK.TryEdu.ModuleSettingBlazor.csproj" />
	</ItemGroup>

	<!--<ItemGroup>
		<BlazorWebAssemblyLazyLoad Include="SLK.TryEdu.ModuleEmployeeBlazor.wasm" />
		<BlazorWebAssemblyLazyLoad Include="SLK.TryEdu.ModuleManagementBlazor.wasm" />
		<BlazorWebAssemblyLazyLoad Include="SLK.TryEdu.ModuleSettingBlazor.wasm" />
	</ItemGroup>-->
</Project>